
GET http://localhost:3001/api/notes
###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "123",
    "important": true
}
###
DELETE http://localhost:3001/api/notes/6487c4a7744d0989add15179

### 
PUT http://localhost:3001/api/notes/6482dc6713e59ed43d8f556c
Content-Type: application/json

{
    "important": true
}
